buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath 'com.guardsquare:proguard-gradle:7.6.0'
	}
}

plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

loom {
	accessWidenerPath = file("src/main/resources/minigamesmod.accesswidener")
}

version = project.mod_version
group = project.maven_group

repositories {
	maven { url "https://api.modrinth.com/maven" }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	modImplementation "maven.modrinth:modmenu:${project.modmenu_version}"
	modImplementation "maven.modrinth:cloth-config:${project.cloth_config_version}"
	modImplementation fileTree(dir: 'libs', include: ['*.jar'])
}

processResources {
	def version = project.version
	inputs.property "version", version
	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName
	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

task obfuscateMod(type: proguard.gradle.ProGuardTask) {
	configuration 'proguard-rules.pro'

	injars remapJar.archiveFile

	outjars "build/libs/${project.name}-${version}-obf.jar"

	if (System.getProperty('java.home') != null) {
		libraryjars "${System.getProperty('java.home')}/jmods"
	}

	dependsOn remapJar
}

build.dependsOn obfuscateMod

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}
	repositories {
	}
}
